from prompts.tutor_prompts import (
    TUTOR_SYSTEM_PROMPT,
    TUTOR_CONCEPT_TEMPLATE,
    TUTOR_QUESTION_TEMPLATE,
    TUTOR_ANALOGY_TEMPLATE
)
from prompts.quiz_prompts import (
    QUIZ_SYSTEM_PROMPT,
    QUIZ_MCQ_TEMPLATE,
    QUIZ_TRUE_FALSE_TEMPLATE,
    QUIZ_FILL_BLANK_TEMPLATE,
    QUIZ_MIXED_TEMPLATE
)
from prompts.summary_prompts import (
    SUMMARIZER_SYSTEM_PROMPT,
    SUMMARIZER_BULLET_TEMPLATE,
    SUMMARIZER_STUDY_GUIDE_TEMPLATE,
    SUMMARIZER_CONDENSED_TEMPLATE,
    SUMMARIZER_HIERARCHICAL_TEMPLATE
)

__all__ = [
    'TUTOR_SYSTEM_PROMPT',
    'TUTOR_CONCEPT_TEMPLATE',
    'TUTOR_QUESTION_TEMPLATE',
    'TUTOR_ANALOGY_TEMPLATE',
    'QUIZ_SYSTEM_PROMPT',
    'QUIZ_MCQ_TEMPLATE',
    'QUIZ_TRUE_FALSE_TEMPLATE',
    'QUIZ_FILL_BLANK_TEMPLATE',
    'QUIZ_MIXED_TEMPLATE',
    'SUMMARIZER_SYSTEM_PROMPT',
    'SUMMARIZER_BULLET_TEMPLATE',
    'SUMMARIZER_STUDY_GUIDE_TEMPLATE',
    'SUMMARIZER_CONDENSED_TEMPLATE',
    'SUMMARIZER_HIERARCHICAL_TEMPLATE'
]
