import asyncio
import sys
import os
import streamlit as st
from dotenv import load_dotenv

# Add project root to sys.path to allow importing from 'src'
# We need to go up from src/app.py to root
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

# Load env
load_dotenv()

# Use absolute imports from the 'src' package
from src.wrapper import UnifiedLLM
from src.models import LLMRequest, Message, Role
from src.providers.openai_provider import OpenAIProvider
from src.providers.anthropic_provider import AnthropicProvider
from src.providers.gemini_provider import GeminiProvider

st.set_page_config(page_title="LLM API Wrapper", page_icon="🤖", layout="wide")
st.title("🤖 Unified LLM API Wrapper")

# Sidebar Configuration
with st.sidebar:
    st.header("Configuration")
    
    # Provider Selection
    provider_option = st.selectbox(
        "Select Provider",
        ["Auto (Fallback Mode)", "OpenAI", "Anthropic", "Gemini"]
    )
    
    selected_provider_key = None
    if provider_option == "OpenAI":
        selected_provider_key = "openai"
    elif provider_option == "Anthropic":
        selected_provider_key = "anthropic"
    elif provider_option == "Gemini":
        selected_provider_key = "gemini"
        
    st.divider()
    
    # Model Settings
    temperature = st.slider("Temperature", 0.0, 1.0, 0.7)
    max_tokens = st.number_input("Max Tokens", min_value=1, max_value=8192, value=1024)
    
    st.divider()
    # Other Settings
    use_streaming = st.checkbox("Enable Streaming", value=True)
    
    st.divider()
    st.caption("Active Providers initialized from .env")

# Initialize Session State
if "messages" not in st.session_state:
    st.session_state.messages = []

if "llm" not in st.session_state:
    try:
        st.session_state.llm = UnifiedLLM()
    except Exception as e:
        st.error(f"Failed to initialize LLM: {e}")

# Display Chat History
for message in st.session_state.messages:
    with st.chat_message(message.role.value):
        st.markdown(message.content)

# Chat Input
if prompt := st.chat_input("What is up?"):
    # Add user message to state
    user_msg = Message(role=Role.USER, content=prompt)
    st.session_state.messages.append(user_msg)
    
    # Display user message
    with st.chat_message("user"):
        st.markdown(prompt)

    # Generate Response
    with st.chat_message("assistant"):
        message_placeholder = st.empty()
        full_response = ""
        
        # Convert messages to dicts to avoid Pydantic class mismatch issues on Streamlit reload
        messages_dicts = [msg.model_dump() for msg in st.session_state.messages]
        request = LLMRequest(
            messages=messages_dicts,
            temperature=temperature,
            max_tokens=max_tokens,
            stream=use_streaming
        )
        
        try:
            if use_streaming:
                # Helper for async iteration in sync context
                async def run_stream():
                    current_text = ""
                    last_chunk = None
                    placeholder = st.empty()
                    async for chunk in st.session_state.llm.stream_async(request, provider_name=selected_provider_key):
                        current_text += chunk.content_delta
                        placeholder.markdown(current_text + "▌")
                        last_chunk = chunk
                    placeholder.markdown(current_text)
                    return current_text, last_chunk

                full_response, last_chunk = asyncio.run(run_stream())
                
                if last_chunk:
                    caption = f"Generated by {last_chunk.provider} ({last_chunk.model_name})"
                    if last_chunk.usage:
                        caption += f" | Total Tokens: {last_chunk.usage.total_tokens} (In: {last_chunk.usage.input_tokens}, Out: {last_chunk.usage.output_tokens})"
                    st.caption(caption)
            else:
                # Non-streaming path
                async def run_generate():
                    return await st.session_state.llm.generate_async(request, provider_name=selected_provider_key)
                
                with st.spinner("Generating response..."):
                    response = asyncio.run(run_generate())
                
                full_response = response.content
                st.markdown(full_response)
                
                caption = f"Generated by {response.provider} ({response.model_name})"
                if response.usage:
                    caption += f" | Total Tokens: {response.usage.total_tokens} (In: {response.usage.input_tokens}, Out: {response.usage.output_tokens})"
                st.caption(caption)
                
        except Exception as e:
            st.error(f"Error generating response: {e}")
            full_response = "I encountered an error."
            
        except Exception as e:
            st.error(f"Error generating response: {e}")
            full_response = "I encountered an error."

    # Add assistant message to state
    st.session_state.messages.append(Message(role=Role.ASSISTANT, content=full_response))
    
    # Force rerun to update state properly if needed (usually handled by st interaction)
