import asyncio
import argparse
import sys
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel
from rich.prompt import Prompt
from rich.live import Live

from .wrapper import UnifiedLLM
from .models import LLMRequest, Message, Role

console = Console()

async def main():
    parser = argparse.ArgumentParser(description="LLM API Wrapper CLI")
    parser.add_argument("--provider", type=str, help="Specific provider to use (openai, anthropic, gemini)", default=None)
    parser.add_argument("--stream", action="store_true", help="Enable streaming", default=True)
    parser.add_argument("--temperature", type=float, help="Temperature", default=0.7)
    args = parser.parse_args()

    console.print(Panel.fit("[bold blue]LLM API Wrapper CLI[/bold blue]", border_style="blue"))

    try:
        llm = UnifiedLLM()
    except Exception as e:
        console.print(f"[bold red]Error initializing LLM Wrapper:[/bold red] {e}")
        return

    if not llm.providers:
        console.print("[bold red]No providers available. Please check your .env file.[/bold red]")
        return
    
    active_provider_names = [p.__class__.__name__ for p in llm.providers]
    console.print(f"[green]Active Providers:[/green] {', '.join(active_provider_names)}")

    messages = []

    while True:
        try:
            user_input = Prompt.ask("\n[bold green]You[/bold green]").strip()
            if not user_input:
                continue
                
            if user_input.lower() in ('exit', 'quit'):
                break
                
            messages.append(Message(role=Role.USER, content=user_input))
            request = LLMRequest(
                messages=messages,
                temperature=args.temperature,
                stream=args.stream
            )

            console.print("\n[bold purple]Assistant[/bold purple]")
            
            full_response = ""
            
            # Corrected indentation and logic for metadata display
            provider_used = ""
            model_used = ""
            usage_info = ""
            
            if args.stream:
                with Live(Markdown(""), refresh_per_second=10) as live:
                    async for chunk in llm.stream_async(request, provider_name=args.provider):
                        full_response += chunk.content_delta
                        live.update(Markdown(full_response))
                        provider_used = chunk.provider
                        model_used = chunk.model_name
                        if chunk.usage:
                            usage_info = f" | Total Tokens: {chunk.usage.total_tokens} (In: {chunk.usage.input_tokens}, Out: {chunk.usage.output_tokens})"
                
                console.print(f"\n[dim italic]Generated by {provider_used} ({model_used}){usage_info}[/dim italic]")

            else:
                with console.status("[bold green]Generating...[/bold green]"):
                    response = await llm.generate_async(request, provider_name=args.provider)
                    full_response = response.content
                    console.print(Markdown(full_response))
                    
                    usage_info = ""
                    if response.usage:
                        usage_info = f" | Total Tokens: {response.usage.total_tokens} (In: {response.usage.input_tokens}, Out: {response.usage.output_tokens})"
                    console.print(f"\n[dim italic]Generated by {response.provider} ({response.model_name}){usage_info}[/dim italic]")
            
            # Add assistant response to history
            messages.append(Message(role=Role.ASSISTANT, content=full_response))
            
            # Show token usage if available (only for non-stream for now or if we track it)
            # console.print(f"\n[dim]Tokens used: ...[/dim]")

        except KeyboardInterrupt:
            console.print("\n[yellow]Exiting...[/yellow]")
            break
        except Exception as e:
            console.print(f"\n[bold red]Error:[/bold red] {e}")

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
